# version: '3.8'
services:
  # 1. new CSDL SQL Server
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-db
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Kh@ng22012004' 
    ports:
      - "1434:1433" # Open port 1433 
    volumes:
      - mssql-data:/var/opt/mssql

  # 2. Backend API service
  backend-api:
    build:
      context: ./UrlShortener 
    container_name: shortener-api-service
    ports:
      - "5000:8080"
    restart: unless-stopped
    depends_on:
      - mssql-db 
    environment:

      ConnectionStrings__DefaultConnection: "Server=mssql-db;Database=UrlShortenerDb_Docker;User Id=sa;Password=Kh@ng22012004;TrustServerCertificate=True;"

  # 3. Frontend UI service
  frontend-ui:
    build:
      context: ./url-shortener-ui
    container_name: shortener-ui-service
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend-api

# save new CSDL
volumes:
  mssql-data: